// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { JupyterDownloadColabNotebookData, JupyterDownloadColabNotebookErrors, JupyterDownloadColabNotebookResponses, JupyterUploadFileData, JupyterUploadFileErrors, JupyterUploadFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload File
 */
export const jupyterUploadFile = <ThrowOnError extends boolean = false>(options: Options<JupyterUploadFileData, ThrowOnError>) => {
    return (options.client ?? client).post<JupyterUploadFileResponses, JupyterUploadFileErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/v1/jupyter/uploadfile/',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Download Colab Notebook
 */
export const jupyterDownloadColabNotebook = <ThrowOnError extends boolean = false>(options: Options<JupyterDownloadColabNotebookData, ThrowOnError>) => {
    return (options.client ?? client).post<JupyterDownloadColabNotebookResponses, JupyterDownloadColabNotebookErrors, ThrowOnError>({
        url: '/api/v1/jupyter/colab/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
