// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://phas0102-converter-api.vercel.app' | (string & {});
};

/**
 * Body_jupyter-download_colab_notebook
 */
export type BodyJupyterDownloadColabNotebook = {
    /**
     * Url
     */
    url: string;
};

/**
 * Body_jupyter-upload_file
 */
export type BodyJupyterUploadFile = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type JupyterUploadFileData = {
    body: BodyJupyterUploadFile;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/api/v1/jupyter/uploadfile/';
};

export type JupyterUploadFileErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JupyterUploadFileError = JupyterUploadFileErrors[keyof JupyterUploadFileErrors];

export type JupyterUploadFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type JupyterDownloadColabNotebookData = {
    body: BodyJupyterDownloadColabNotebook;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/api/v1/jupyter/colab/';
};

export type JupyterDownloadColabNotebookErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JupyterDownloadColabNotebookError = JupyterDownloadColabNotebookErrors[keyof JupyterDownloadColabNotebookErrors];

export type JupyterDownloadColabNotebookResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
